

--Insert statements for 2 new users of your system
SET IDENTITY_INSERT dbo.Users ON;
INSERT USERS (UserId, FullName, Email, PhoneNumber, RegistrationDate) 
VALUES ('407','Bill Clinton','BillClinton@gmail.com','555-554-0330','2018-09-23'),
('408','Jimmy Carter','PresJimCarter@aol.com','555-553-0072','2018-02-22')

SET IDENTITY_INSERT dbo.Users OFF;

--Inert statments for reservations by these two new people for 4 day stays at one of your campgrounds


SET IDENTITY_INSERT dbo.Reservations ON;
INSERT Reservations (ResId, CampsiteId, UserId, ReservationDate) 
VALUES ('538','10','407','2019-05-01'),
('539','10','407','2019-05-02'),
('540','10','407','2019-05-03'),
('541','10','407','2019-05-04'),
('542','6','408','2019-07-12'),
('544','6','408','2019-05-13'),
('545','6','408','2019-05-14'),
('546','6','408','2019-05-15')
SET IDENTITY_INSERT dbo.Reservations OFF;


/*A query that returns all camp spots for one of your campgrounds, 
	showing the amenities and availability for each.  
Write this query to cover one of the reservations you created above.
*/

SELECT
	DISTINCT CampsiteName, AmenityDescription
FROM 
(
	SELECT 
		CS.CampsiteName,
		CS.CampsiteId [CampsiteId],
		AM.AmenityDescription,
		CS.Capacity
	FROM 
		dbo.Campsites CS
	INNER JOIN dbo.CampsitesToAmenities CTA ON CS.CampsiteId = CTA.CampsiteId
	INNER JOIN dbo.Amenity AM ON CTA.AmenityId = AM.AmenityId
	WHERE 
		CS.CampgroundId = 2
)CSI
INNER JOIN dbo.Reservations RES ON RES.CampsiteId = CSI.CampsiteId
WHERE 
	RES.ReservationDate NOT BETWEEN '2019-05-01' AND '2019-05-02'


/*A query that shows how many days each spot for one of your campgrounds were reserved for a given date range.  
  Include the % utilization in this query 
  (i.e. if the date range is 30 days and the spot was reserved for 15 days in that date range, utilization is 50%)
*/

DECLARE @AmountOfDaysSearched DECIMAL
SET @AmountOfDaysSearched = DATEDIFF(DAY, '2019-01-01', '2020-01-01')

SELECT 
	NCSI.DaysReserved, 
	CS.CampsiteName, 
	CG.CampGroundName, 
	CONCAT(CAST(((NCSI.DaysReserved/@AmountOfDaysSearched)*100) AS DECIMAL(16,2)), '%') [PercentReserved]
FROM
(
	SELECT 
		COUNT(CampsiteId) [DaysReserved], CampsiteId [siteId]
	FROM 
		dbo.Reservations RES
	WHERE 
		RES.ReservationDate BETWEEN '2019-01-01' AND '2020-01-01'
	GROUP BY 
		CampsiteId
)NCSI
INNER JOIN dbo.CampSites CS ON NCSI.siteId = CS.CampsiteId
INNER JOIN dbo.Campgrounds CG ON CS.CampgroundId = CG.CampGroundId


/*
Write a query that shows the revenue generated by each campground, 
broken out by month for June, July, August, and September.
*/


SELECT
	DATENAME(MONTH, DATEADD(MONTH,TGIF.ReserveMonth,0)-1) [ReserveMonth], 
	TGIF.CGName [CampName],
	CONCAT('$',SUM(TGIF.CampRevenue)) [TotalRevenue]
FROM
(
	SELECT 
		NCSI.DaysReserved [NumDaysRes], 
		CS.CampsiteId [SiteId], 
		CG.CampGroundName [CGName],
		CS.Price * NCSI.DaysReserved [CampRevenue],
		NCSI.ReserveMonth
	FROM
	(
		SELECT 
			COUNT(CampsiteId) [DaysReserved], 
			CampsiteId [siteId],
			MONTH(ReservationDate) [ReserveMonth],
			YEAR(ReservationDate) [ReserveYear]
		FROM 
			dbo.Reservations RES
		WHERE 
			(
				MONTH(ReservationDate) = '6'
			OR
				MONTH(ReservationDate) = '7'
			OR
				MONTH(ReservationDate) = '8'
			OR
				MONTH(ReservationDate) = '9'
			)
		AND
			YEAR(ReservationDate) = '2019'
		GROUP BY 
			CampsiteId,
			MONTH(ReservationDate),
			YEAR(ReservationDate)
		
	)NCSI
	INNER JOIN dbo.CampSites CS ON NCSI.siteId = CS.CampsiteId
	INNER JOIN dbo.Campgrounds CG ON CS.CampgroundId = CG.CampGroundId
)TGIF
GROUP BY
	TGIF.CGName,
	TGIF.ReserveMonth


